# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"J\n\x0ePredictRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x14\n\x0chorizon_days\x18\x02 \x01(\x05\x12\x10\n\x08outcomes\x18\x03 \x03(\t\"(\n\x0fPredictResponse\x12\x15\n\rprobabilities\x18\x01 \x03(\x01\x32W\n\x11PredictionService\x12\x42\n\x07Predict\x12\x1a.ai_service.PredictRequest\x1a\x1b.ai_service.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=106
  _globals['_PREDICTRESPONSE']._serialized_start=108
  _globals['_PREDICTRESPONSE']._serialized_end=148
  _globals['_PREDICTIONSERVICE']._serialized_start=150
  _globals['_PREDICTIONSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
